version: '3.8'
name: tallemalle

services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ../db:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=tallemalle
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
  
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile-backend
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - DB_URL=jdbc:mariadb://db:3306/tallemalle
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile-frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_WS_URL=${VITE_WS_URL}
        - VITE_KAKAO_MAP_KEY=${VITE_KAKAO_MAP_KEY}
    ports:
      - "80:80"
    depends_on:
      - backend
