# 빌드
FROM gradle:8.14.4-jdk17 AS builder
WORKDIR /app
COPY tallemalle-be/build.gradle ./
COPY tallemalle-be/settings.gradle ./
RUN gradle dependencies --no-daemon
COPY tallemalle-be/src ./src
RUN gradle bootJar

# 실행
FROM openjdk:17-ea-17-slim
COPY --from=builder /app/build/libs/*jar /app.jar
EXPOSE 8080
CMD ["java", "-jar", "/app.jar"]
