# 빌드
FROM node:24.12.0-slim AS builder
WORKDIR /app

# Docker Compose에서 넘겨주는 빌드 인자(args) 정의
ARG VITE_API_BASE_URL
ARG VITE_WS_URL
ARG VITE_KAKAO_MAP_KEY

# 빌드 시점에 환경 변수로 등록 (Vite가 이를 참조하여 빌드함)
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_WS_URL=${VITE_WS_URL}
ENV VITE_KAKAO_MAP_KEY=${VITE_KAKAO_MAP_KEY}

COPY tallemalle-fe/package.json ./
RUN npm install
COPY tallemalle-fe/ ./
RUN npm run build


# 실행
FROM nginx:alpine
# 빌드 컨텍스트가 루트이므로 infra/ 폴더에서 직접 복사 가능
COPY infra/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
