name: deployment
on:
  push:
    branches: [main]
  jobs:
    deply:
      name: deploy
      runs-on: ubuntu-latest
      steps:
        - name: run ssh
          uses: applyboy/ssh-action@v1
          with:
            host: ${{secrets.HOST}}
            username: ${{secrets.USERNAME}}
            key: ${{secrets.SSH_KEY}}
            port: ${{sercets.PORT}}
            script: |
              echo test > /tmp/test